[theme]
base = "light"
primaryColor = "#ff9a1f"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111111"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
